### ISSUE TITLE
Sending events to Slanger with the Pusher PHP Library not work

### ISSUE THREAD

**Issue by luilope1** [stevegraham/slanger#172]
Hello,
Hi, I change server and I can not run slanger, I development with JS and PHP.
1.	gem install slanger
2.	redis-server &> /dev/null &
3.	slanger --app_key 999999999 --secret 88888888 –v
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]
all is ok. Server is up and running.
then I have two basic pages :
**HTML / JS**
```
<script type="text/javascript" src="http://js.pusher.com/2.2/pusher.min.js"></script>
    <script type="text/javascript">  
var pusher = new Pusher(‘9999999999’, {
        wsHost: "94.xxx.xxx.xxx",
        wsPort: "8080",
        wssPort: "8080",
        enabledTransports: ['ws'],
        log: function(data) {
          console.log('\t\t', data);
       }
      });
      pusher.bind('pusher:error', function(data) { alert(data['message']) })
      var myChannel = pusher.subscribe('my-channel');
       myChannel.bind('my-event', function(data) {
            console.log(data);
    });
    </script>
```
**PHP**
```
         include('Pusher2.2.php');
        $key="99999999999";
        $secret="888888888888";
        $app_id="123456";
        $pusher = new Pusher($key, $secret, $app_id,array('debug' => 'true'),'94.xxx.xxx.xxx,'4567');
        $sal= $pusher->trigger('my-channel', 'my-event', 'hello luis' );
        print_r($sal);
```
**When execute page1 html**
```
Running Slanger v.0.4.0 Slanger API server listening on port 4567 Slanger WebSocket server listening on port 8080 FiberError - double resume: /usr/local/lib/ruby/gems/2.1.0/gems/slanger-0.4.0/lib/slanger/api_server.rb:65:in `resume' /usr/local/lib/ruby/gems/2.1.0/gems/slanger-0.4.0/lib/slanger/api_server.rb:65:in `block (2 levels) in publish' 
/usr/local/lib/ruby/gems/2.1.0/gems/eventmachine-1.0.4/lib/em/deferrable.rb:74:in `call' /usr/local/lib/ruby/gems/2.1.0/gems/eventmachine-1.0.4/lib/em/deferrable.rb:74:in `errback' /usr/local/lib/ruby/gems/2.1.0/gems/slanger-0.4.0/lib/slanger/api_server.rb:65:in `block in publish' /usr/local/lib/ruby/gems/2.1.0/gems/slanger-0.4.0/lib/slanger/api_server.rb:63:in `tap' /usr/local/lib/ruby/gems/2.1.0/gems/slanger-0.4.0/lib/slanger/api_server.rb:63:in `publish' /usr/local/lib/ruby/gems/2.1.0/gems/slanger-0.4.0/lib/slanger/api_server.rb:29:in `block (2 levels) in ' /usr/local/lib/ruby/gems/2.1.0/gems/slanger-0.4.0/lib/slanger/api_server.rb:29:in `each' /usr/local/lib/ruby/gems/2.1.0/gems/slanger-0.4.0/lib/slanger/api_server.rb:29:in `block in ' /usr/local/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call' 
/usr/local/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!' /usr/local/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]' /usr/local/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!' /usr/local/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval' /usr/local/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!' /usr/local/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route' /usr/local/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch' /usr/local/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route' /usr/local/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!' /usr/local/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each' /usr/local/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!' 
/usr/local/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!' /usr/local/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke' /usr/local/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch' /usr/local/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke' /usr/local/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!' /usr/local/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!' /usr/local/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke' /usr/local/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch' 
/usr/local/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke' /usr/local/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!' /usr/local/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call' 
/usr/local/lib/ruby/gems/2.1.0/gems/rack-fiber_pool-0.9.3/lib/rack/fiber_pool.rb:22:in `block in call' /usr/local/lib/ruby/gems/2.1.0/gems/rack-fiber_pool-0.9.3/lib/fiber_pool.rb:48:in `call' /usr/local/lib/ruby/gems/2.1.0/gems/rack-fiber_pool-0.9.3/lib/fiber_pool.rb:48:in `block (3 levels) in initialize' /usr/local/lib/ruby/gems/2.1.0/gems/rack-fiber_pool-0.9.3/lib/fiber_pool.rb:47:in `loop' /usr/local/lib/ruby/gems/2.1.0/gems/rack-fiber_pool-0.9.3/lib/fiber_pool.rb:47:in `block (2 levels) in initialize'
```
**Then I clone the repository and execute:** bundle update slanger.
**I execute:**
slanger --app_key 999999999 --secret 88888888 –v
```
WARN: Unresolved specs during Gem::Specification.reset:
      eventmachine (>= 0.12.9, ~> 1.0, ~> 1.0.0)
      tilt (>= 1.3.4, ~> 1.3)
      addressable (>= 2.0.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.


    .d8888b.  888
   d88P  Y88b 888
   Y88b.      888
    "Y888b.   888  8888b.  88888b.   .d88b.   .d88b.  888d888
       "Y88b. 888     "88b 888 "88b d88P"88b d8P  Y8b 888P"
         "888 888 .d888888 888  888 888  888 88888888 888
   Y88b  d88P 888 888  888 888  888 Y88b 888 Y8b.     888
    "Y8888P"  888 "Y888888 888  888  "Y88888  "Y8888  888
                                         888
                                    Y8b d88P
                                    "Y88P"


Running Slanger v.0.4.0

Slanger API server listening on port 4567
Slanger WebSocket server listening on port 8080
```
**When execute page1 html**
```
[[:initialize]]

[[:receive_data,
  "GET /app/3347dfd01bb616347b83?protocol=6&client=js&version=2.0.5&flash=false
HTTP/1.1\r\nHost: 94.xxx.xxx.xxx:8080\r\nConnection: Upgrade\r\nPragma: no-cache\r
\nCache-Control: no-cache\r\nUpgrade: websocket\r\nOrigin: http://localhost\r\nS
ec-WebSocket-Version: 13\r\nUser-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) Appl
eWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36\r\nAccept-
Encoding: gzip, deflate, sdch\r\nAccept-Language: es-ES,es;q=0.8,ca;q=0.6\r\nCoo
kie: cookieWarningDisplayed1=1; _zsit3=s3qm8rtl7n7h97ijb1of0bf3dq32s3ip; __utma=
218063006.807969204.1422291455.1423166206.1423304088.22; __utmz=218063006.142229
1455.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)\r\nSec-WebSocket-Key: efu
jj4PKI3v9Mrqt9HYhlA==\r\nSec-WebSocket-Extensions: permessage-deflate; client_ma
x_window_bits\r\n\r\n"]]

[[:accepting_ws_version, 13]]

[[:upgrade_response,
  "HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade
\r\nSec-WebSocket-Accept: zfkxb9eyIcM/YhlpUXn0plUumxc=\r\n\r\n"]]

[[:sending_frame,
  :text,
  "{\"event\":\"pusher:connection_established\",\"data\":\"{\\\"socket_id\\\":\\
\"cd92e366-c831-405a-879a-05eaf1e74320\\\",\\\"activity_timeout\\\":120}\"}"]]

[[:receive_data,
  "\x81\xBC\xAA\xFC\xAD\x11\xD1\xDE\xC8g\xCF\x92\xD93\x90\xDE\xDDd\xD9\x94\xC8c\
x90\x8F\xD8s\xD9\x9F\xDFx\xC8\x99\x8F=\x88\x98\xCCe\xCB\xDE\x97j\x88\x9F\xC5p\xC
4\x92\xC8}\x88\xC6\x8F|\xD3\xD1\xCEy\xCB\x92\xC3t\xC6\xDE\xD0l"]]

[[:message_received,
  :text,
  "{\"event\":\"pusher:subscribe\",\"data\":{\"channel\":\"my-channel\"}}"]]

[[:sending_frame,
  :text,
  "{\"event\":\"pusher_internal:subscription_succeeded\",\"data\":\"{}\",\"chann
el\":\"my-channel\"}"]]
```
**When execute page2 PHP**
I only see:
```
        $sal= $pusher->trigger('my-channel', 'my-event', 'hello luis' );
        print_r($sal) **Array ( [body] => {} [status] => 202 )**
```
And nothing in the console slanger

**Comment by stevegraham** [comment]
0.4.0 isn't the latest code on master. I've now released 0.4.1. Please try that.

**Comment by luilope1** [comment]
Hi Steve,
I installed the 0.4.1 version and this is the result:

slanger --app_key 999999999--secret 88888888888 -v

```
    .d8888b.  888
   d88P  Y88b 888
   Y88b.      888
    "Y888b.   888  8888b.  88888b.   .d88b.   .d88b.  888d888
       "Y88b. 888     "88b 888 "88b d88P"88b d8P  Y8b 888P"
         "888 888 .d888888 888  888 888  888 88888888 888
   Y88b  d88P 888 888  888 888  888 Y88b 888 Y8b.     888
    "Y8888P"  888 "Y888888 888  888  "Y88888  "Y8888  888
                                         888
                                    Y8b d88P
                                    "Y88P"


Running Slanger v.0.4.1

Slanger API server listening on port 4567
Slanger WebSocket server listening on port 8080
[[:initialize]]

[[:receive_data,
  "GET /app/999999999?protocol=6&client=js&version=2.0.5&flash=false
HTTP/1.1\r\nHost: 94.xxx.xxx.xxx:8080\r\nConnection: Upgrade\r\nPragma: no-cache\r
\nCache-Control: no-cache\r\nUpgrade: websocket\r\nOrigin: http://www.languagefo
rexchange.com\r\nSec-WebSocket-Version: 13\r\nUser-Agent: Mozilla/5.0 (Windows N
T 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari
/537.36\r\nAccept-Encoding: gzip, deflate, sdch\r\nAccept-Language: es-ES,es;q=0
.8,ca;q=0.6\r\nCookie: cookieWarningDisplayed1=1; _zsit3=s3qm8rtl7n7h97ijb1of0bf
3dq32s3ip; __utma=218063006.807969204.1422291455.1423166206.1423304088.22; __utm
z=218063006.1422291455.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)\r\nSec-
WebSocket-Key: W+1Q6aU+vP5fEA1eLWrCiA==\r\nSec-WebSocket-Extensions: permessage-
deflate; client_max_window_bits\r\n\r\n"]]

[[:accepting_ws_version, 13]]

[[:upgrade_response,
  "HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade
\r\nSec-WebSocket-Accept: PHOUV+C1CSPiTzf2A3syOVLf9LM=\r\n\r\n"]]

[[:sending_frame,
  :text,
  "{\"event\":\"pusher:connection_established\",\"data\":\"{\\\"socket_id\\\":\\
\"0df30196-3971-41e1-b589-3af7161b49f1\\\",\\\"activity_timeout\\\":120}\"}"]]

[[:receive_data,
  "\x81\xBC\x1A\xC92'a\xEBWQ\x7F\xA7F\x05 \xEBBRi\xA1WU \xBAGEi\xAA@Nx\xAC\x10\v
8\xADSS{\xEB\b\\8\xAAZFt\xA7WK8\xF3\x10Jc\xE4QO{\xA7\\Bv\xEBOZ"]]

[[:message_received,
  :text,
  "{\"event\":\"pusher:subscribe\",\"data\":{\"channel\":\"my-channel\"}}"]]

[[:sending_frame,
  :text,
  "{\"event\":\"pusher_internal:subscription_succeeded\",\"data\":\"{}\",\"chann
el\":\"my-channel\"}"]]
```
PHP Version 5.5.21
The CURL in Pusher.php (current version 2.2 from https://github.com/pusher/pusher-php-server ) 

when I execute
```
  include('Pusher2.2.php');
        $key="99999999999";
        $secret="888888888888";
        $app_id="123456";
        $pusher = new Pusher($key, $secret, $app_id,array('debug' => 'true'),'94.xxx.xxx.xxx,'4567');
        $sal= $pusher->trigger('my-channel', 'my-event', 'hello luis' );
```
I see:
**$sal=Array ( [body] => {} [status] => 202 )**

and any message in the console slanger.
Where is the error?

Thank You.

**Comment by sirthom** [comment]
Same problem here since 0.4.1, version 0.4.0 was good. Status 202.

**Comment by sirthom** [comment]
i commented out these lines from api_server.rb and it works: "status 202"
