### ISSUE TITLE
 Slanger::Api::InvalidRequest - no body:

### ISSUE THREAD

**Issue by bvandermeersch** [stevegraham/slanger#208]
Hello,

I get this error when passing an API call to slanger:

Slanger::Api::InvalidRequest - no body:
        /usr/local/lib/ruby/gems/2.3.0/gems/slanger-0.6.0/lib/slanger/api/request_validation.rb:45:in `validate!'
        /usr/local/lib/ruby/gems/2.3.0/gems/slanger-0.6.0/lib/slanger/api/request_validation.rb:9:in `initialize'
        /usr/local/lib/ruby/gems/2.3.0/gems/slanger-0.6.0/lib/slanger/api/server.rb:52:in `new'
        /usr/local/lib/ruby/gems/2.3.0/gems/slanger-0.6.0/lib/slanger/api/server.rb:52:in `valid_request'
        /usr/local/lib/ruby/gems/2.3.0/gems/slanger-0.6.0/lib/slanger/api/server.rb:24:in `block in <class:Server>'
        /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
        /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
        /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
        /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
        /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
        /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:965:in `block in filter!'
        /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:965:in `each'
        /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:965:in `filter!'
        /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1083:in `block in dispatch!'
        /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
        /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
        /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
        /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
        /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
        /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
        /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
        /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
        /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
        /usr/local/lib/ruby/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
        /usr/local/lib/ruby/gems/2.3.0/gems/rack-fiber_pool-0.9.3/lib/rack/fiber_pool.rb:22:in `block in call'
        /usr/local/lib/ruby/gems/2.3.0/gems/rack-fiber_pool-0.9.3/lib/fiber_pool.rb:48:in `block (3 levels) in initialize'
        /usr/local/lib/ruby/gems/2.3.0/gems/rack-fiber_pool-0.9.3/lib/fiber_pool.rb:47:in `loop'
        /usr/local/lib/ruby/gems/2.3.0/gems/rack-fiber_pool-0.9.3/lib/fiber_pool.rb:47:in `block (2 levels) in initialize'

Any in-site into this? It works fine through pusher but when I try slanger I get that error.

Here is what the API call looks like:

https://pusher.XXXX.com:4567/apps/155854/events?auth_key=XXXXXXX&auth_signature=710d4983faa3e6db1bee120c10bc74df167c78b3a85d21f76fa2fe42326a18f8&auth_timestamp=1456956882&auth_version=1.0&body_md5=b8b651c7e1ae3c0493329c3b0b2c5020 

The auth signature is there and the md5 so not sure why it wont work. I dont think the order of them is an issue.

**Comment by bvandermeersch** [comment]
We update the php library as it was out of date. But still no luck.

Here is some more info that may or may not help:

curl -v https://pusher.XXXX.com:4567/apps/155854/events?auth_key=XXXXXXXXXX&auth_signature=710d4983faa3e6db1bee120c10bc74df167c78b3a85d21f76fa2fe42326a18f8&auth_timestamp=1456956882&auth_version=1.0&body_md5=b8b651c7e1ae3c0493329c3b0b2c5020
[1] 24590
[2] 24591
[3] 24592
[4] 24593
[2]   Done                    auth_signature=710d4983faa3e6db1bee120c10bc74df167c78b3a85d21f76fa2fe42326a18f8
[3]-  Done                    auth_timestamp=1456956882
bill-iMac:peatio-slanger bill$ * Hostname was NOT found in DNS cache
*   Trying XX.250.XXX.82...
* Connected to pusher.XXXXX.com (XX.250.XXX.82) port 4567 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
* Server certificate: pusher.XXXXX.com
* Server certificate: AlphaSSL CA - SHA256 - G2
* Server certificate: GlobalSign Root CA
> GET /apps/155854/events?auth_key=XXXXXXXXXXXX HTTP/1.1
> User-Agent: curl/7.37.1
> Host: pusher.XXXXX.com:4567
> Accept: */*
> 
< HTTP/1.1 400 Bad Request
< Content-Type: text/html;charset=utf-8
< Content-Length: 15
* Server thin is not blacklisted
< Server: thin
< 
* Connection #0 to host pusher.person.com left intact
400 Bad Request
[1]-  Done                    curl -v https://pusher.XXXXX.com:4567/apps/155854/events?auth_key=XXXXXXXXXX
[4]+  Done                    auth_version=1.0

**Comment by bvandermeersch** [comment]
@stevegraham any thoughts on this?

**Comment by MathiasDewelde** [comment]
I have exactly the same problem...

**Comment by oklas** [comment]
Does anybody try to do this as POST request?
I meet same error with ruby livrary with code: `Pusher.get_async("/channels")` from [documentation](https://github.com/pusher/pusher-http-ruby/)

This error disappear when I change `get` to `post` like this: `Pusher.get_async("/channels")`

Error is disappear and all is work silently with no errors and no crash.
(But I do not try to take profit from this api call. I turned onto another way and get profit with `trigger` method)
There is useful to keep on mind that most of pusher clients libraries is "only for server" or "only for client application".

**Comment by wardcraigj** [comment]
I'm also seeing this issue when trying to get channel info. Trying as a post request as suggested didn't work either
