### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by vitorgamer58** [stevegraham/slanger#235]
i get this erro

```
    .d8888b.  888                                               
   d88P  Y88b 888                                               
   Y88b.      888                                               
    "Y888b.   888  8888b.  88888b.   .d88b.   .d88b.  888d888   
       "Y88b. 888     "88b 888 "88b d88P"88b d8P  Y8b 888P"     
         "888 888 .d888888 888  888 888  888 88888888 888       
   Y88b  d88P 888 888  888 888  888 Y88b 888 Y8b.     888       
    "Y8888P"  888 "Y888888 888  888  "Y88888  "Y8888  888       
                                         888                    
                                    Y8b d88P                    
                                    "Y88P"                      


Running Slanger v.0.6.0

Slanger API server listening on port 4567
Slanger WebSocket server listening on port 8080
2018-07-13 13:40:35 - Slanger::Api::InvalidRequest - no body:
	/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/slanger-0.6.0/lib/slanger/api/request_validation.rb:45:in `validate!'
	/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/slanger-0.6.0/lib/slanger/api/request_validation.rb:9:in `initialize'
	/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/slanger-0.6.0/lib/slanger/api/server.rb:52:in `new'
	/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/slanger-0.6.0/lib/slanger/api/server.rb:52:in `valid_request'
	/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/slanger-0.6.0/lib/slanger/api/server.rb:24:in `block in <class:Server>'
	/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
	/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
	/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `[]'
	/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
	/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
	/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
	/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:965:in `block in filter!'
	/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:965:in `each'
	/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:965:in `filter!'
	/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1083:in `block in dispatch!'
	/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
	/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
	/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
	/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
	/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
	/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
	/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-fiber_pool-0.9.3/lib/rack/fiber_pool.rb:22:in `block in call'
	/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-fiber_pool-0.9.3/lib/fiber_pool.rb:48:in `call'
	/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-fiber_pool-0.9.3/lib/fiber_pool.rb:48:in `block (3 levels) in initialize'
	/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-fiber_pool-0.9.3/lib/fiber_pool.rb:47:in `loop'
	/home/deploy/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-fiber_pool-0.9.3/lib/fiber_pool.rb:47:in `block (2 levels) in initialize'
```

**Comment by aviadeToroX** [comment]
I have the same error with no clear reason.

**Comment by vitorgamer58** [comment]
@aviadeToroX are you trying to install Peatio ?

**Comment by aviadeToroX** [comment]
Yes. i was playing around with peatio and got this error.

Are you doing the same thing ?
